import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EdWorld Academy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) { 
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="top-0 left-0 w-screen sticky z-10">
        <Navbar />
      </div>
        {children}
        </body>
    </html>
  )
}
